server:
  context-path: /aop
  jsp-servlet:
    init-parameters:
      development: true
  port: 8082
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
    encoding:
      charset: utf-8
      force: true
mybatis:
  type-aliases-package: com.zzy.entity
  mapper-locations: Mapper/*Mapper.xml
